### ISSUE TITLE
Inferno v4 is launching soon

### ISSUE THREAD

**Issue by Havunen** [zanettin/incompose#14]
Hi

We are about to launch inferno v4. I believe this library needs to be updated.
For breaking changes see: https://github.com/infernojs/inferno/tree/docs-v4

**Comment by zanettin** [comment]
thx for your hint. gonna check it asap.

**Comment by zanettin** [comment]
working on it => https://github.com/zanettin/incompose/pull/15

**Comment by zanettin** [comment]
first beta `2.0.0-beta.0` just published. waiting for testing feedback.

**Comment by zanettin** [comment]
released as `2.0.0` 👍
