### ISSUE TITLE
Error when trying to import shouldUpdate

### ISSUE THREAD

**Issue by gilesbutler** [zanettin/incompose#2]
Hey,

I'm getting the following error when trying to import shouldUpdate:
```
Failed to compile.

Error in ./~/incompose/dist/withLifecycle.js
Module not found: 'inferno-create-element' in /Users/.../node_modules/incompose/dist

 @ ./~/incompose/dist/withLifecycle.js 14:28-61
```
Any ideas?

Thanks

**Update:**
I also get it if I try to use named imports:
```
import {
  compose,
  withState
} from 'incompose';
```
But default imports work:
```
import compose from 'incompose/dist/compose';
import withState from 'incompose/dist/withState';
```

**Comment by zanettin** [comment]
Hi @gilesbutler 

Yes, this is an unmet dependency which i have to fix.
Pls run `npm install --save inferno-create-element` or `yarn add inferno-create-element`.
This should fix it.

Sry for the inconvinience!

**Comment by gilesbutler** [comment]
Great thanks @zanettin

**Comment by gilesbutler** [comment]
Thanks for the super fast response too ;)

**Comment by zanettin** [comment]
you're welcome 😄  happy incomposing 👍

**Comment by zanettin** [comment]
@gilesbutler just launched v.0.0.10 which should fix this issue. can you please upgrade to the latest version, remove `inferno-create-element` from your package.json and run `rm -rf node_modules && npm i` on your app root?
if you're using yarn and working on a demo app, pls remove also the `yarn.lock` file 👍
