### ISSUE TITLE
Error when withState is composed

### ISSUE THREAD

**Issue by ioi0** [zanettin/incompose#23]
Deps:
```
"@babel/core": "^7.4.4",
"incompose": "^4.0.0-alpha.1",
"inferno": "^7.1.12",
```

To reproduce:
```
import { compose, withProps } from 'incompose';

export default compose(
  withProps({ foo: 'bar '}),
  withState('state', 'setState', null),
)(() => <span>Dummy template</span>);
```

In this case `withProps` hoc will try to call returned class from `withState` as a function.

Babel will throw error: `TypeError: Cannot call a class as a function`

**Comment by ioi0** [comment]
PR: https://github.com/zanettin/incompose/pull/24

**Comment by zanettin** [comment]
deployed on version 5.0.0. thanks for your contribution 🎉
